FROM node:20-slim AS base

ENV PNPM_HOME="/pnpm"
ENV PATH="$PNPM_HOME:$PATH"

RUN corepack enable
COPY . /home/node/app
WORKDIR /home/node/app
RUN chown node:node /home/node/app
RUN apt-get update -y && apt-get install -y openssl


FROM base AS runner
USER node
CMD [ "pnpm", "run", "start:dev" ]