
services:
  infra-postgres:
    image: bitnami/postgresql:17
    environment:
      - POSTGRES_USER=psql_user
      - POSTGRES_PASSWORD=psql_pass
      - POSTGRES_DB=lumi_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/bitnami/postgresql
    healthcheck:
      test: pg_isready --host=127.0.0.1 --port=5432 --dbname=lumi_db --username=psql_user
      start_period: "5s"
      interval: "5s"
      timeout: "5s"
      retries: 5

  app-backend:
    build: 
      context: ./../../projects/backend
      dockerfile: config/docker/Dockerfile.dev
    environment:
      - NODE_ENV=development
      - HTTP_PORT=3000
      - HTTP_HOST=0.0.0.0
      - POSTGRES_URL=postgres://psql_user:psql_pass@infra-postgres:5432/lumi_db
    ports:
      - '3000:3000'
    # volumes:
    #   - ./../../projects/backend:/app
    depends_on:
      - infra-postgres
    healthcheck:
      test:
        ["CMD", "curl", "-s", "http://$$HTTP_HOST:$$HTTP_PORT/api/healthcheck"]
      interval: 5s
      timeout: 5s
      retries: 5


  app-frontend:
    build: 
      context: ./../../projects/frontend
      dockerfile: config/docker/Dockerfile.dev
    environment:
      - NEXT_PUBLIC_API_URL=http://app-backend:3000
    ports:
      - '3001:3000'
    # volumes:
    #   - ./../../projects/frontend:/app
    depends_on:
      - app-backend

volumes:
  postgres_data:
